# Generated by Django 5.0.6 on 2025-03-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_remove_crop_farmer_remove_crop_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
